SAMPLES = ['A', 'B']

rule all:
    input:
        expand('work/quantify_genes/{sample}.txt', sample=SAMPLES)

rule quantify_genes:
    input:
        genome = 'data/ref/genome.fa',
        r1 = 'data/fastq/{sample}.R1.fastq.gz',
        r2 = 'data/fastq/{sample}.R2.fastq.gz'
    output:
        'work/quantify_genes/{sample}.txt'
    shell:
        'echo {input.genome} {input.r1} {input.r2} > {output}'
